controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_offer:
    path: /offer/
    controller: App\Controller\OfferController::index
    methods: [GET, POST] # Ajouter la méthode GET
